### ISSUE TITLE
move documentation from wiki to git

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#626]
Having the docs in the wiki is convenient, and allows for convenient updates by anyone in the world, but introduces problems keeping the documentation synchronized with the code. This was most apparent during the current long-running 2.0.0 release cycle, but I've noticed it other times as well.
If we moved the documentation into the code, and used something like [Read the Docs](https://readthedocs.org/) to host our documentation, we'd be able to 

1. Update the documentation at the same time the code was changing. Ideally whoever was contributing a fix or enhancement would also update the documentation, but we could do so in a superseding PR if needed. This would ease our cognitive load, and help reduce the work needed to release a new version - no more scrambling at the last minute to make sure the docs are correct.
2. Make available different versions of the documentation, for those stuck using older versions of the library
3. Not have to worry so much about footnotes or the fancy "[Version 1.x | Version  2.x]" selectors on pages.

I'd be inclined to put product documentation in the source. You know, things that relate directly to using FakeItEasy and may change release by release.
I think keeping the contributor / owner docs in the wiki makes more sense. 

Changes I'd like to make before publishing Please push back if there's anything that doesn't make sense

- [x] tidy everything up as best I can
- [x] create separate branches for working on the [1.25.3](http://bfakeiteasy.readthedocs.org/en/read-the-docs-1.25.3/) and [2.0](http://bfakeiteasy.readthedocs.org/en/read-the-docs-2.0/) versions
- [x] in the 1.25.3 branch, move all the "in 1.x" topics to replace their "unversioned" twin (see [Raising Events](https://github.com/FakeItEasy/FakeItEasy/wiki/Raising-Events) for a sample, if you don't know what I'm talking about)
- [x] remove from the 2.0.0 documentation all the notes that refer to how things changed between 1.x versions. Like the footnotes on the Bootstrapper page. We'd be making the 2.0.0 documents a clean break from the 1.x version. The 1.25.3 documentation could retain these
- [x] reference to "Running multithreaded unit tests with FakeItEasy" from the 2.0.0 version of the "External Resources" page. We shouldn't need it.
- [x] remove "Slow startup time" from the 2.0.0 documentation. The issues we knew about have been addressed, and there have been no complaints for a long time. With no reason to assume that this will be a problem again, why devote space to it?
- [x] remove "Upgrading from older versions" from the 2.0.0 documentation? It handles one very specific task that will need to be done to upgrade from an old version, ignoring nearly everything else.
- [x] send PRs, to universal acclaim (1.25.3: #627, 2.0: #628)
- [x] add better styling to the 2.0 version, as was included in 1.25.3 (#635)
- [x] update ReadTheDocs project. I suggest having "stable" be the default view, but making sure we also build the "latest" docs.
- [x] remove "Changes in 2.0" from the documentation, putting in release notes ( #636)
- [x] remove content from wiki, pointing at ReadTheDocs
- [x] make issue for web site, to point at ReadTheDocs (FakeItEasy/fakeiteasy.github.io#28)

**Comment by blairconrad** [comment]
I downloaded the wiki pages and did a very small amount of styling.
With nearly no effort expended, I have teasers!

![image](https://cloud.githubusercontent.com/assets/3275797/13701654/6344fffa-e757-11e5-9834-941a2b601a44.png)

![image](https://cloud.githubusercontent.com/assets/3275797/13701661/7346e9e0-e757-11e5-8f94-029c63772380.png)

**Comment by blairconrad** [comment]
as you can see, the wiki-style links ([[implicit creation options…]]) would need fixing, but I'm more than happy to put that kind of effort in.

**Comment by thomaslevesque** [comment]
> What do you think?

I completely agree with your suggestion


> I downloaded the wiki pages and did a very small amount of styling.
> With nearly no effort expended, I have teasers!

Looks great! :+1:

**Comment by blairconrad** [comment]
w00t!

I think there may also be benefit in moving the release notes to committed files, but one issue at a time.

And now, just to make things more interesting, if @adamralph signs onto the overall idea of moving the docs, I think it would be good to have this done in time for the 2.0.0 release. That way we can say all 2.x+ documentation is in readthedocs or whatever.

Oh, there's the lingering concern of what to do with the 1.x docs. We could leave them in the wiki, with a warning. I'm not sure how to move them to readthedocs without adding a commit that's tagged with a 1.x.y label… I may dig for more information on alternatives.

**Comment by thomaslevesque** [comment]
> I think it would be good to have this done in time for the 2.0.0 release

Sounds good to me

> Oh, there's the lingering concern of what to do with the 1.x docs. We could leave them in the wiki, with a warning. I'm not sure how to move them to readthedocs without adding a commit that's tagged with a 1.x.y label… I may dig for more information on alternatives.

We could just add the 1.x documentation in a new 1.x branch (based on the last 1.x.y tag)

**Comment by blairconrad** [comment]
My thought as well, but wasn't sure how it would sit on everyone's "ideal vs. pragmatic" scale.

**Comment by thomaslevesque** [comment]
> My thought as well, but wasn't sure how it would sit on everyone's "ideal vs. pragmatic" scale.

Well, I'd say it's both pragmatic and ideal :wink: (at least I can't see any obvious drawback)

**Comment by blairconrad** [comment]
If we want the docs to show up as "1.25.3", I think we'd need to tag with 1.25.3, and that tag already exists. If we moved it, it would no longer correspond exactly to the state of the repo that we released build 1.25.3 from.

The _parts that matter_ would be the same. Just not everything.

**Comment by adamralph** [comment]
I love it. I'm also a huge fan of https://readthedocs.org/ and I already played with it for FIE - https://readthedocs.org/projects/fakeiteasy/

If the 1.x docs are problematic because of the tag, then I suggest we leave them where they are in the wiki and start with 2.0 in readthedocs.

**Comment by adamralph** [comment]
Actually, for 1.x we can use the branching approach. We just create a support-1 branch at the current 1.25.3 commit, add a docs-only commit to it and then just move the tag.

**Comment by thomaslevesque** [comment]
> If the 1.x docs are problematic because of the tag

Maybe I'm missing something obvious, but I don't really understand what the problem is. Does it have something to do with how ReadTheDocs works?

> then I suggest we leave them where they are in the wiki and start with 2.0 in readthedocs.

If we leave the 1.x docs in the wiki, I'm worried people will often look in the wrong place when looking for the docs...

**Comment by adamralph** [comment]
@blairconrad @thomaslevesque if you give me your account names for readthedocs then I'll make you co-owners of the project.

**Comment by adamralph** [comment]
@thomaslevesque

Maybe I'm missing something obvious, but I don't really understand what the problem is. Does it have something to do with how ReadTheDocs works?

Yes, readthedocs generates documents by building from tags in the GitHub repo, so if we want docs versioned 1.25.3 then they need to be built from that tag in the repo. However, the commit which has that tag has no docs content. So, we'd need to branch off from that tag (I suggest a "support-1" branch) add a commit to add the docs content and then move the tag to that commit, then rebuild the docs in readthedocs.

> If we leave the 1.x docs in the wiki, I'm worried people will often look in the wrong place when looking for the docs...

Agreed, I'm :+1: to go with the hacked tag approach.

**Comment by thomaslevesque** [comment]
Ah, I see.

Moving tags is probably not a good habit, but in this case I think it's ok, as long as we're not touching the code.

**Comment by thomaslevesque** [comment]
> @blairconrad @thomaslevesque if you give me your account names for readthedocs then I'll make you co-owners of the project.

I just created mine: _thomaslevesque_

(I expected readthedocs to support GitHub OAuth login, but sadly it doesn't)

**Comment by adamralph** [comment]
> as long as we're not touching the code

That's the key to the hack. :smile: 

We have to be very careful that the commit only adds the docs content.

**Comment by blairconrad** [comment]
> @blairconrad @thomaslevesque if you give me your account names for readthedocs then I'll make you co-owners of the project.

blairconrad!

Like @thomaslevesque, I was surprised at having to "create an account". I was griping about it to a coworker.

> Actually, for 1.x we can use the branching approach. We just create a support-1 branch at the current 1.25.3 commit, add a docs-only commit to it and then just move the tag.

Oh, good. That was my thought. I feared it wouldn't be pure enough for you, @adamralph.

**Comment by blairconrad** [comment]
My work-in-progress can be seen at http://bfakeiteasy.readthedocs.org/.

That's what will become the 2.0 version. I've exported the wiki pages, cleaned up the formatting, added titles to the top, and changed the internal links (the wiki format did not work).
I'm about to give them a read-over, just to make sure things look good and all the links are still valid and whatnot.

I'd like your opinion on some things, @adamralph and @thomaslevesque:

1. I'm inclined to remove from the 2.0.0 documentation all the notes that refer to how things changed between 1.x versions. Like the footnotes on [the Bootstrapper page](https://github.com/FakeItEasy/FakeItEasy/wiki/Bootstrapper). We'd be making the 2.0.0 documents a clean break from the 1.x version.
2. Moving forward, we _could_ add notes about the evolution of behaviour in 2.x, if we're so inclined. Although maybe with ReadTheDocs ability to host different versions of the documentation, there's less need.
3. Since there will be no pre-1.25.3 versions of the documentation, I would keep the footnotes in the 1.25.3 of the documents, which I'll produce after the 2.0.0 version.

All sound okay?

**Comment by thomaslevesque** [comment]
Great job @blairconrad!

> I'm inclined to remove from the 2.0.0 documentation all the notes that refer to how things changed between 1.x versions. Like the footnotes on the Bootstrapper page. We'd be making the 2.0.0 documents a clean break from the 1.x version.

It would probably be useful to have a page showing all the changes in 2.0.0, to make it easier for people to migrate to 2.x. If the information is scattered on many different pages, it will be harder to find.

**Comment by blairconrad** [comment]
There is the [Changes in version 2.0](http://bfakeiteasy.readthedocs.org/en/read-the-docs-2.0/changes-in-version-2.0/) page. Is that what you're suggesting, @thomaslevesque?
Although I wonder if we wouldn't (and it doesn't have to be done in in this step) be better off just putting the release notes in an .md and having it included in the docs.

**Comment by blairconrad** [comment]
Ah. I understand @thomaslevesque's concern now. I had meant to remove the notes from all the individual topic pages, but to retain the "Changes in 2.0" page. Sorry for being unclear.

**Comment by thomaslevesque** [comment]
Ah, ok. In this case I agree, there's no reason to keep the notes on individual topic pages.

**Comment by adamralph** [comment]
> I'm inclined to remove from the 2.0.0 documentation all the notes that refer to how things changed between 1.x versions. Like the footnotes on the Bootstrapper page. We'd be making the 2.0.0 documents a clean break from the 1.x version.

I agree.

> Moving forward, we could add notes about the evolution of behaviour in 2.x, if we're so inclined. Although maybe with ReadTheDocs ability to host different versions of the documentation, there's less need.

I don't think we need to. People can look at old versions of the docs if they want (as you say, an advantage of using readthedocs).

> Since there will be no pre-1.25.3 versions of the documentation, I would keep the footnotes in the 1.25.3 of the documents, which I'll produce after the 2.0.0 version.

I agree.

btw - the code snippets in the documentation look rather horrible. Is there any way we can get them formatted nicely?

**Comment by adamralph** [comment]
I think we should put http://bfakeiteasy.readthedocs.org/en/read-the-docs-2.0/changes-in-version-2.0/ into the 2.0 release notes and remove it form readthedocs.

**Comment by blairconrad** [comment]
@adamralph, that works for me. Release notes in the release, or release notes in the source? I kind of like the idea of an ever-growing release notes documentation page. (Which could potentially be used to automate parts of the release and nuget package building…)

**Comment by adamralph** [comment]
To avoid immediately taking on more work, I think we should keep our release notes as they are for now. I.e. just in GitHub releases and copied to the NuGet. The "changes in 2.0" wiki page was a special addition for this release, and I'm not really sure why we didn't just target it for release notes in the first place.

Release notes in the source is an interesting concept which I've seen used elsewhere, but I think it's better to visit that separately, perhaps after we've released 2.0.

**Comment by blairconrad** [comment]
Happy to wait to move release notes to source.

One reason to have put "changes in 2.0" in the wiki is that, until the release is published, nobody else can read the release notes.

**Comment by blairconrad** [comment]
Also, as it is, the 2.0.0 contains a terser version of the "what's changed in 2.0". Not too much trouble to put the latter in the release notes instead, although we'll need to reformat to work nicely with NuGet's release notes styling (no styling).

**Comment by adamralph** [comment]
> One reason to have put "changes in 2.0" in the wiki is that, until the release is published, nobody else can read the release notes.

True, but I guess we could have put it in the first alpha/beta/RC release notes.

> although we'll need to reformat to work nicely with NuGet's release notes styling (no styling)

Yeah, that's rather a shortcoming in the NuGet gallery. We could consider just putting the URL to the GitHub release notes in there instead. It won't be a hyperlink :unamused: but at least it will save the duplication and reformatting.

**Comment by blairconrad** [comment]
@adamralph said

> btw - the code snippets in the documentation look rather horrible. Is there any way we can get them formatted nicely?

I'm not in love with them either. They appear to be made using the fairly popular [highlight.js](https://highlightjs.org/) formatter, with the "GitHub" theme.

Oddly enough, this is exactly what I use on my blog, and I've never been terribly put out about them.
It's possible to add an extra .css file to change the styling.

What about it bothers you specifically? Colours? Fonts?
I'm happy to try to [adjust it](http://www.mkdocs.org/user-guide/styling-your-docs/#built-in-themes) to more closely match the GitHub wiki's styling. I can make the font Consolas throughout (instead of class names in Courier) and _try_ to do some things about the colour.

**Comment by blairconrad** [comment]
Hm. Ignore the "class name" comment. But colours and bolding could be adjusted, I think.

**Comment by blairconrad** [comment]
I've updated the formatting of the code blocks and inline code as well, and pushed to the [1.25.3 docs](http://bfakeiteasy.readthedocs.org/en/read-the-docs-1.25.3/), since we've got to get that right anyhow.
Better?

**Comment by thomaslevesque** [comment]
> Better?

I didn't pay attention to how it looked before the change, but anyway it looks fine now :+1:

**Comment by blairconrad** [comment]
@thomaslevesque, you can contrast with the [2.0 docs](http://bfakeiteasy.readthedocs.org/en/read-the-docs-2.0/), if you're so inclined.

**Comment by adamralph** [comment]
@blairconrad the formatting in the 1.25.3 version looks much better. The red text with line outlines is really jarring, i.e.

![image](https://cloud.githubusercontent.com/assets/677704/14106639/ed84d2f8-f5b2-11e5-9116-92bb552f22ab.png)

compared with

![image](https://cloud.githubusercontent.com/assets/677704/14106647/f87cea7e-f5b2-11e5-971c-ea0bb7f2bd9b.png)

It would be nice to get C# syntax highlighting but that can come later, if it's even possible.

**Comment by thomaslevesque** [comment]
> It would be nice to get C# syntax highlighting but that can come later, if it's even possible.

What do you mean? Syntax highlighting is already there:

![screenshot](http://i.imgur.com/R6N5MaJ.png)

**Comment by adamralph** [comment]
Hmmm, I don't see it. See my screenshot above - all black and white.

**Comment by adamralph** [comment]
Ah, false alarm. I had JS disabled. All good now :smile: 

(That also made 2.0.0 look better, but 1.25.3 is way better still.)

**Comment by blairconrad** [comment]
I didn't love the original highlighting, but didn't think it was as bad as all that. Now that I see what you saw, I understand the comment.

And I'm glad you said that 1.25.3 is way better. I'd've hated to think that I spent all that time last night correlating GitHub wiki class names with highlight.js class names so I could copy colour codes for nothing.

**Comment by blairconrad** [comment]
From the checklist upstairs:

> update ReadTheDocs project. I suggest having "stable" be the default view, but making sure we also build the "latest" docs.

This seems to be in place now. Checking.

**Comment by adamralph** [comment]
Agreed, stable should be the default. Each time we release a major we can also explicitly build the previous major tag, so that people can still access it.

**Comment by adamralph** [comment]
Waffle auto-magically assigned me when I raised #650.

I've raised an issue with Waffle for turning off this auto-magic - https://github.com/waffleio/waffle.io/issues/2479

**Comment by adamralph** [comment]
@blairconrad do you need any help with:

> - [ ] remove content from wiki, pointing at ReadTheDocs

?

**Comment by blairconrad** [comment]
@adamralph, I'm happy for you or anyone to go ahead. It's not that it's overly difficult (I think), but I've been distracted by the other issues.
If you'd rather not do it, but are bothered by it being open, I can move it to the top of the list.

**Comment by adamralph** [comment]
@blairconrad I'll see what I can do.

It's not so much "bothered by it being open" but more ["what's left to do to release 2.0"](https://waffle.io/adamralph/adamralph.github.com?source=FakeItEasy%2FFakeItEasy,FakeItEasy%2Ffakeiteasy-assets,FakeItEasy%2Ffakeiteasy.github.io&milestone=2.0.0).

**Comment by adamralph** [comment]
All done!

**Comment by blairconrad** [comment]
Not to complain, but I'd've thought the readme's Documentation link wouldn't point at the wiki anymore.

**Comment by adamralph** [comment]
Oops!

**Comment by blairconrad** [comment]
Are we planning on retaining the "Changes in 2.0" wiki topic forever, or just until we actually release, when people can read the release notes?
If forever, it's full of broken links!

**Comment by adamralph** [comment]
I almost removed it, but then I thought I'd leave it in until the release is published. Good point about the broken links :grin: 

It's a shame we can't make the draft release public. Perhaps we should copy the contents of the draft release into that wiki page for now, to fix the links?

**Comment by adamralph** [comment]
Is there any reason that the draft release is not using fenced code blocks (but the wiki page is)?

**Comment by blairconrad** [comment]
My memory is fuzzy, but the draft release was probably recreated from the readthedocs docs before they were removed, and it doesn't like the fenced code blocks in lists.

**Comment by blairconrad** [comment]
I've added fenced code blocks to the release notes and copied to the wiki.

**Comment by blairconrad** [comment]
I probably should've just put it in the wiki and made the release notes a pointer to the wiki (for now).

**Comment by adamralph** [comment]
:+1: thanks v much @blairconrad

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
